# Generated by Django 4.2.1 on 2023-05-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='cost_to_print',
        ),
        migrations.RemoveField(
            model_name='product',
            name='filament_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
